# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    logging:
        driver: none
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build: './'
    volumes: 
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db